<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0"
    xmlns="http://www.tei-c.org/ns/1.0" xpath-default-namespace="http://www.tei-c.org/ns/1.0"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:sch="http://purl.oclc.org/dsdl/schematron"
    xmlns:rng="http://relaxng.org/ns/structure/1.0">
    <xsl:output method="xml" indent="yes"/>
    <xsl:template match="/">
        <xsl:processing-instruction name="xml-model">href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"</xsl:processing-instruction>
        <xsl:processing-instruction name="xml-model">href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_odds.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"
        </xsl:processing-instruction>
        <TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:xi="http://www.w3.org/2001/XInclude"
            xmlns:sch="http://purl.oclc.org/dsdl/schematron"
            xmlns:rng="http://relaxng.org/ns/structure/1.0"
            version="2.9.1"
            xml:lang="en">
            <teiHeader>
                <fileDesc>
                    <titleStmt>
                        <title>Digital Mitford ODD: Prosopography Reference Addendum for Project Edition Files</title>
                        <author>Elisa Beshero-Bondar</author>
                    </titleStmt>
                    <editionStmt xml:id="edition"><edition>Generated on <xsl:value-of select="current-dateTime()"/> from updates to the <xsl:apply-templates select="descendant::teiHeader//editionStmt/edition"/></edition>
                    </editionStmt>
                    <publicationStmt>
                        <authority>Prepared in TEI P5 by Elisa Beshero-Bondar in the Digital Mitford GitHub repository: <ref target="https://github.com/DigitalMitford/DM_processing"/>. Date last worked on: <date when="2018-08-06">6 August 2018</date></authority>
                        <availability><licence>Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) approved for Free Cultural Works <ref target="https://creativecommons.org/licenses/by-sa/4.0/"/></licence></availability>
                    </publicationStmt>
                    <seriesStmt>
                        <p>The additional materials in this ODD are designed to be incorporated into the Digital Mitford main ODD file by means of automated inclusion. In the oXygen XML editor this may be done using Tools --> Canonicalize on the main Mitford ODD file. This ODD addendum file is also designed to be generated by XSLT from the Digital Mitford Site Index. </p>
                    </seriesStmt>
                    <sourceDesc>
                        <p>Born digital, based on information presented in the Digital Mitford Codebook at <ref target="http://codebook.mitford.pitt.edu"/></p>
                    </sourceDesc>
                </fileDesc>
                <revisionDesc>
                    <listChange>
                        <change when="2018-08-06" who="#ebb">Prepared this ODD file, working with the Digital Mitford Site Index file official at this point.</change>
                    </listChange>
                </revisionDesc>
            </teiHeader>
            <text>
                <body>
                    <schemaSpec ident="mrmProsop" start="TEI teiCorpus" prefix="tei">
                        <specGrp xml:id="prosop">
                            <elementSpec ident="persName" module="namesdates" mode="change">
                            <attList>
                                <attDef ident="ref" mode="replace" usage="req">
                                 <valList type="closed">   
                                     <xsl:apply-templates select="descendant::text//listPerson//@xml:id"/>
                                 </valList>
                                </attDef>
                            </attList>    
                            </elementSpec>
                            <elementSpec ident="orgName" module="namesdates" mode="change">
                                <attList>
                                    <attDef ident="ref" mode="replace" usage="req">
                                        <valList type="closed">   
                                            <xsl:apply-templates select="descendant::text//listOrg//@xml:id"/>
                                        </valList>
                                    </attDef>
                                </attList>    
                            </elementSpec>
                            <elementSpec ident="placeName" module="namesdates" mode="change">
                                <attList>
                                    <attDef ident="ref" mode="replace" usage="req">
                                        <valList type="closed">   
                                            <xsl:apply-templates select="descendant::text//listPlace//@xml:id"/>
                                        </valList>
                                    </attDef>
                                </attList>    
                            </elementSpec>
                            <elementSpec ident="title" module="core" mode="change">
                                <attList>
                                    <attDef ident="ref" mode="replace" usage="req">
                                        <valList type="closed">   
                                            <xsl:apply-templates select="descendant::text//listBibl//@xml:id"/>
                                            <xsl:apply-templates select="descendant::text//list[@sortKey='art']//@xml:id"/>
                                        </valList>
                                    </attDef>
                                </attList>    
                            </elementSpec>
                            <elementSpec ident="bibl" module="core" mode="change">
                                <attList>
                                    <attDef ident="corresp" mode="replace" usage="req">
                                        <valList type="closed">   
                                            <xsl:apply-templates select="descendant::text//listBibl//@xml:id"/>
                                        </valList>
                                    </attDef>
                                </attList>    
                            </elementSpec>
                            <elementSpec ident="name" module="core" mode="change">
                                <attList>
                                    <attDef ident="type" mode="replace" usage="req">
                                        <valList type="closed">
                                            <valItem ident="plant"><gloss>Use to mark names of plants by kind, variety, genus, and/or species. If the mention is imprecise and you want to mark a short string of text as referring to a plant, use the rs element with type="plant".</gloss></valItem>
                                            <valItem ident="animal"><gloss>Use to mark references to animal types by kind, variety, genus, and/or species. If the mention is imprecise and you want to mark a short string of text as referring to a kind of animal, use the rs element with type="animal". </gloss></valItem>
                                            <valItem ident="event"><gloss>Use to mark names of events, like the Battle of Hastings. If the mention is imprecise and you want to mark a short string of text as referring to a specific event, use the rs element with type="event". </gloss></valItem>
                                        </valList>
                                    </attDef>
                                    <attDef ident="ref" mode="replace" usage="req">
                                        <valList type="closed">   
                                            <xsl:apply-templates select="descendant::text//listEvent//@xml:id"/>
                                            <xsl:apply-templates select="descendant::text//list//@xml:id"/>
                                        </valList>
                                    </attDef>
                                </attList>    
                            </elementSpec>
                        </specGrp>
                    </schemaSpec>
                </body>
            </text>
        </TEI>
    </xsl:template>
    <xsl:template match="@xml:id">
        <valItem ident="#{.}"/>
    </xsl:template>
    
    
</xsl:stylesheet>